//
//  DeveloperPreview.swift
//  Airbnb-Clone
//
//  Created by Berkay Yaşar on 13.11.2023.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listing: [Listing] = [
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Alexandra YASAR", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 6, numberOfBeds: 3, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-la-1", "listing-la-2", "listing-la-3"], adress: "67 Main St", city: "Los Angeles", state: "California", title: "LA Villa", rating: 4.5, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Taylor Bond", ownerImageUrl: "female-profile-photo-2", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.35, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "John Smith", ownerImageUrl: "male-profile-photo-1", numberOfBedrooms: 2, numberOfBathrooms: 1, numberOfGuests: 4, numberOfBeds: 3, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-ny-1", "listing-ny-2"], adress: "124 Main St", city: "Manhattan", state: "New York", title: "NY Apartment", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .apartment),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "George Lucas", ownerImageUrl: "female-profile-photo-3", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-4-miami", "listing-2-miami", "listing-3-miami", "listing-1-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.22, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Brad Pitt", ownerImageUrl: "male-profile-photo-1", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-la-2", "listing-la-1", "listing-la-3"], adress: "223 Main St", city: "Los Angeles", state: "California", title: "LA Villa", rating: 4.75, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "James Bond", ownerImageUrl: "male-profile-photo-1", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-3-miami", "listing-2-miami", "listing-1-miami", "listing-4-miami"], adress: "32 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 3.95, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Victoria Pedretti", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-ny-2", "listing-ny-1"], adress: "124 Main St", city: "Manhattan", state: "New York", title: "NY Villa", rating: 4.16, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Angelina Jolie", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-la-3", "listing-la-1", "listing-la-2"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.54, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Timothy Chalamet", ownerImageUrl: "male-profile-photo-1", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-2-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 3.67, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Scarlett Johanson", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 3.88, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
    ]
}
