//
//  DeveloperPreview.swift
//  Airbnb-Clone
//
//  Created by Berkay Yaşar on 13.11.2023.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listing: [Listing] = [
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Taylor Bond", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Berkay YASAR", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-2-miami", "listing-1-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Los Angeles", state: "California", title: "LA Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "John Smith", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-3-miami", "listing-2-miami", "listing-1-miami", "listing-4-miami"], adress: "124 Main St", city: "Manhattan", state: "New York", title: "NY Apart", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "George Lucas", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-4-miami", "listing-2-miami", "listing-3-miami", "listing-1-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Brad Pitt", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "James Bond", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Victoria Pedretti", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Angelina Jolie", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Timothy Chalamet", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Scarlett Johanson", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Elizabeth Olsen", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        .init(id: NSUUID().uuidString, ownerUid: NSUUID().uuidString, ownerName: "Leonardo diCaprio", ownerImageUrl: "female-profile-photo", numberOfBedrooms: 4, numberOfBathrooms: 3, numberOfGuests: 4, numberOfBeds: 4, pricePerNight: 567, latitude: 25.7850, longitude: -80.1936, imageURLs: ["listing-1-miami", "listing-2-miami", "listing-3-miami", "listing-4-miami"], adress: "124 Main St", city: "Miami", state: "Florida", title: "Miami Villa", rating: 4.86, features: [.selfCheckIn, .superhost], amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
    
    ]
}
